env:
  es6: true
  node: true

plugins:
  - jest

extends:
  - airbnb-base
  - plugin:jest/recommended

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules: {
  no-console: 0,
  import/extensions: 0
}
